# Generated by Django 2.2.7 on 2019-11-17 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_locais'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaco',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='local.Locais'),
            preserve_default=False,
        ),
    ]
