# Generated by Django 2.2.7 on 2019-11-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_espaco_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locais',
            options={'verbose_name_plural': 'Locais'},
        ),
    ]
