# Generated by Django 2.2.7 on 2019-11-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_espaco_local'),
        ('problemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problema',
            name='local',
            field=models.ManyToManyField(to='local.Locais'),
        ),
    ]
