# Generated by Django 2.2.7 on 2019-11-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_espaco_local'),
        ('problemas', '0002_problema_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problema',
            name='local',
        ),
        migrations.AddField(
            model_name='problema',
            name='espaco',
            field=models.ManyToManyField(to='local.Espaco'),
        ),
    ]
