# Generated by Django 2.2.7 on 2019-11-17 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_espaco_local'),
        ('problemas', '0003_auto_20191116_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problema',
            name='espaco',
        ),
        migrations.AddField(
            model_name='problema',
            name='espaco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='local.Espaco'),
            preserve_default=False,
        ),
    ]
